name: Deploy Site

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Public Repository
      uses: actions/checkout@v2

    - name: Checkout Private Repository
      uses: actions/checkout@v2
      with:
        repository: lossecretosdelexito/a
        token: ${{ secrets.PRIVATE_REPO_TOKEN }}
        path: private-repo

    - name: Copy Data from Private Repo
      run: cp -r private-repo/* ./index.html  # Copia todo el contenido, incluyendo index.html

    - name: Deploy to GitHub Pages
      run: |
        git config --global user.name 'GitHub Action'
        git config --global user.email 'action@github.com'
        git add .
        git commit -m "Deploy site"
        git push origin main  # Cambia 'gh-pages' a la rama que usas para GitHub Pages
