
name: Install Dependencies and Forward Port

on:
  pull_request:
    branches:
      - main

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js and Install Dependencies
        uses: actions/setup-node@v2
        with:
          node-version: '12'

      - name: Install npm and nodemon
        run: |
          npm install
          npm install --save-dev nodemon


      - name: Set execute permission for ngrok
        run: chmod +x ./ngrok-v3/ngrok

      - name: Forward Port 8888
        run: ./ngrok-v3/ngrok http 8888
